CREATE TABLE weatherUsers
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login     Varchar (20) UNIQUE NOT NULL,
    password  Varchar (64) NOT NULL
);

CREATE TABLE locations
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      Varchar (128) UNIQUE NOT NULL,
    user_id   BIGINT NOT NULL,
    latitude  DECIMAL,
    longitude DECIMAL,
    FOREIGN KEY (user_id) REFERENCES weatherUsers(id)
);

CREATE TABLE sessions
(
    id   UUID PRIMARY KEY,
    user_id   BIGINT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (user_id) REFERENCES weatherUsers(id)
);

CREATE INDEX idx_sessions_expires_at ON sessions (expires_at);