CREATE TABLE weatherUsers
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login    Varchar(20) UNIQUE NOT NULL CHECK (LENGTH(login) > 1),
    password Varchar(255)        NOT NULL CHECK (LENGTH(password) > 8)
);

CREATE TABLE locations
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      Varchar(128) NOT NULL,
    user_id   BIGINT       NOT NULL,
    latitude  DECIMAL      NOT NULL,
    longitude DECIMAL      NOT NULL,
    FOREIGN KEY (user_id) REFERENCES weatherUsers (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT unique_user_location UNIQUE (user_id, latitude, longitude)
);

CREATE TABLE sessions
(
    id         UUID PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (user_id) REFERENCES weatherUsers (id)
);

CREATE INDEX idx_sessions_expires_at ON sessions (expires_at);